FROM ubuntu:latest
WORKDIR /root
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y cmake build-essential rsync libboost-all-dev libgflags-dev libgmp-dev git ca-certificates libssl-dev
CMD ["sleep", "infinity"]
