services:
  dev_container:
    networks:
      - apt_cache
    image: dev-container
    container_name: dev-container
    ports:
      - "2222:22"
    volumes:
      - src:/root/sources
      - /etc/ssh:/etc/ssh

volumes:
  src:
    name: src

networks:
  apt_cache:
    name: apt_cache
    external: true
